ignore:
  - "Sources/Helper/AdaptiveLayout/*/*.swift"
  - "Sources/Helper/Extension/VectorMath.swift"
  - "Sources/Shared/*.swift"
  - "Tests"
  - "UITests"
  - "Example"
  - "Module"
  - "Submodule"
